### ISSUE TITLE
Talks案

### ISSUE THREAD

**Issue by mactkg** [post-internet/onsen-2015-spring#10]
1hの枠が3枠あります。その中を2人で分けたりしても構いません。とりあえず枠とってあるだけです。
合宿で話せる何かがある人は、大体の時間を書いて、テーマと一緒に投稿してください。
大体 20分~が望ましいかなと思います。15分くらいでも良いかもしれません。

@kvvzr アンケート結果など張っておくと便利かも。

よろしくお願いします。

**Comment by kvvzr** [comment]
DeepLearningの綴りが間違っていてつらい

[アンケート結果](https://docs.google.com/forms/d/1RvwKLZ_bfQ4F9SFCVRWrB2wi_bVGR3T4Mxkfzh8b_n8/viewanalytics?usp=form_confirm)
