### ISSUE TITLE
サクセソン

### ISSUE THREAD

**Issue by mactkg** [post-internet/onsen-2015-spring#8]
## サクセソンとは?

HackathonはHack-malathonから成る造語ですが、サクセソンは作戦:sakusen-malathonから成る造語です。短い時間などのイベントではアイデアソン(Ide-a-thon)になりがちですが、この手法だと実際の実装についてあまり考慮されなかったりすることがあります。サクセソンでは、実装の作戦までも込みにしてアイデアソンを行い、アイディアの面白さと実装の美しさなどに着目します。

アイデアソンでも、実際の実装などについて考慮するグループも少なく無いとは思うのですが、システムとして意識させることで、様々な人がケアするようになるのではないかと思っています。

---

これが基本の考え方です。チームで固定してしまうのも良いとは思うのですが、[ワールドカフェ](http://world-cafe.net/about-wc.html)の手法を取り入れるなどして、オープンに議論を取り合うことも面白いのではないかと考えています。
## Todo
- [ ] 大まかな全体の流れを決める
- [ ] 最終的なアウトプットはなにか?
  - 評価軸はなにか、優劣をつけるのか?
- [ ] メンバーの構成はどうするか
  - ワールドカフェ形式
  - 1st 2nd混合を意識したチーム
  - etc...
- [ ] 必要な物品の洗い出し
  - ポストイット、筆記用具、模造紙…?
- [ ] テーマを決める(決め方、難易度の設定など)

何か提案などあればコメントお願いします! @post-internet/owners @post-internet/1st

**Comment by kvvzr** [comment]
- [ ] テーマを決める(決め方、難易度の設定など)

**Comment by mactkg** [comment]
@kvvzr 最初のpost編集できるんで編集しちゃっても良いよ!? 追記したってことを書いてくれたら良いと思う。

**Comment by kvvzr** [comment]
たし蟹

**Comment by kvvzr** [comment]
追記しました

> テーマを決める(決め方、難易度の設定など)

**Comment by mactkg** [comment]
## 会話
- @kvvzr: 最初はどのチームにも属さずにテーマだけがいくつか与えられて、好きなものにContributionしていく(自分の色付き付箋=コミット)のはどうか
- @mactkg: 同じテーマのほうが、ヤラれた感強くて楽しいかなと思う
  - 「ああそういうアイディアか〜」「そういう実装か〜」みたいな気付き体験
  - 技術で縛らない感じのテーマがよいのでは

**Comment by mactkg** [comment]
age
